server:
  port: 8000

spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fengjingwei/mall.git
          search-paths: spring-cloud-config/src/main/resources
          username: 951159049@qq.com
          password: More201314

