server:
  port: 9886
  address: 0.0.0.0
  servlet:
    context-path: /gateway-service

spring:
  application:
    name: gateway-service
  zipkin:
    base-url: http://192.168.1.135:9413

eureka:
  client:
    service-url:
      default-zone: http://192.168.1.135:8761/eureka/,http://192.168.1.135:8861/eureka/,http://192.168.1.135:8961/eureka/
  instance:
    prefer-ip-address: true
    #instance-id: ${spring.cloud.client.ip-address}:${server.port}

zuul:
  ignoredServices: '*'
  routes:
    order-service:
      path: /order/**
      serviceId: order-service
    account-service:
      path: /account/**
      serviceId: account-service
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
