server:
  port: 9883
  address: 0.0.0.0
  servlet:
    context-path: /inventory-service

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.139:3306/mall_inventory?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    dbcp2:
      initial-size: 20
      min-idle: 20
      max-wait-millis: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
  application:
    name: inventory-service
  zipkin:
    base-url: http://localhost:9412

mybatis:
  type-aliases-package: com.hengxunda.springcloud.inventory.entity
  config-location: classpath:mybatis/mybatis-config.xml

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}